"""Rapport CONTEXT-V2 : autopsie, mécanisme, mesure, limites."""

from __future__ import annotations

from ..analysis.context_v2 import STATES
from .context_test import CASES, compare


def render() -> str:
    resultats = compare()
    base, v2 = resultats["baseline"], resultats["v2"]

    return "\n".join([
        "# CONTEXT-V2 — une information appartient-elle au contexte demandé ?",
        "",
        "## 1. Ce qui n'est pas touché",
        "",
        "H1, H2, ADAPTIVE-V1, ADAPTIVE-V2, RESEARCH-BASELINE, RESEARCH-V2,",
        "EXTRACTION-V2 et les six jeux déjà utilisés : inchangés. CONTEXT-V2 est",
        "un mécanisme **nouveau**, dans un module à part, qui n'est branché sur",
        "aucun d'eux.",
        "",
        "## 2. Autopsie des 16 erreurs de contextualisation",
        "",
        "Fait décisif : **dans les seize cas, la bonne valeur était disponible**.",
        "Le système ne manquait pas d'information — il en avait trop, et il a",
        "servi la mauvaise. Ce n'est donc pas un problème de recherche.",
        "",
        "| Cause | Cas | Part |",
        "|---|---|---|",
        "| **Temps** — page ancienne prise pour l'actuelle | 9 | 56 % |",
        "| **Objet** — autre bien ou service | 3 | 19 % |",
        "| **Géographie** — autre lieu | 2 | 12 % |",
        "| **Géographie** — lieu au nom voisin | 2 | 12 % |",
        "",
        "Le temps domine. L'ordre des contrôles de CONTEXT-V2 en découle :",
        "temps d'abord, géographie ensuite, objet en dernier.",
        "",
        "L'autopsie est rejouable : `ara.lab.autopsy.run_autopsy()`.",
        "",
        "## 3. Le mécanisme",
        "",
        "Quatre états, deux seulement autorisent l'affirmation :",
        "",
        "| État | Sens | Affirmable |",
        "|---|---|---|",
        "| `MATCH` | objet, lieu et période concordent | oui |",
        "| `PROBABLE_MATCH` | le sujet est nommé dans la source, pas dans la phrase | oui |",
        "| `CONTEXT_UNKNOWN` | rien ne rattache l'information au sujet | **non** |",
        "| `MISMATCH` | l'information appartient à un autre contexte | **non** |",
        "",
        "Règle de sécurité : `CONTEXT_UNKNOWN` et `MISMATCH` ne deviennent",
        "jamais une affirmation. Rien n'est jeté pour autant — le filtre rend",
        "deux paniers, et chaque blocage porte sa raison.",
        "",
        "## 4. Jeu 7 — indépendant, écrit avant exécution",
        "",
        f"{len(CASES)} cas, univers neuf (école de musique), neuf familles de",
        "pièges : autre pays, nom homonyme, archive, plusieurs tarifs sur une",
        "page, plusieurs devises, services voisins, autre objet, information",
        "historique, commune limitrophe. Cinq cas sont **corrects** : un jeu",
        "qui ne contiendrait que des pièges récompenserait le rejet aveugle.",
        "",
        "| Mesure | sans contrôle | CONTEXT-V2 |",
        "|---|---|---|",
        f"| Bonnes informations conservées | {base.kept_good}/{base.total_good} "
        f"({base.recall_good:.0%}) | **{v2.kept_good}/{v2.total_good}** "
        f"({v2.recall_good:.0%}) |",
        f"| Mauvaises informations rejetées | {base.rejected_bad}/{base.total_bad} "
        f"({base.rejection_rate:.0%}) | **{v2.rejected_bad}/{v2.total_bad}** "
        f"({v2.rejection_rate:.0%}) |",
        f"| Faux rejets | {base.false_rejects} | **{v2.false_rejects}** |",
        f"| Exactitude finale | {base.accuracy:.0%} | **{v2.accuracy:.0%}** |",
        "",
        "**Zéro faux rejet** : aucune information correcte n'a été écartée.",
        "C'était la condition posée — réduire les erreurs *sans* rejeter le bon.",
        "",
        "### Les quatre pièges qui passent encore",
        "",
        "| Cas | Pourquoi |",
        "|---|---|",
        "| `homonyme` | deux communes partagent un nom : il faudrait un référentiel géographique |",
        "| `autre_instrument` | « école » suffit à rattacher un violon à une question sur une guitare |",
        "| `service_voisin` | « cours » suffit à rattacher le solfège au piano |",
        "| `page_multi_tarifs_mauvais` | le bon objet est ailleurs sur la page, la phrase parle d'autre chose |",
        "",
        "Trois d'entre eux ont **la même cause** : le contrôle d'objet se",
        "contente d'un seul terme partagé, sans le peser. Le corriger exigerait",
        "de savoir que « violon » et « guitare » s'excluent, et que « école » ne",
        "distingue rien — donc une version suivante, avec son propre jeu.",
        "",
        "Chacun de ces quatre cas a un test qui **fige le comportement actuel**.",
        "S'il se met à échouer, c'est que quelqu'un a progressé.",
        "",
        "## 5. CONTEXT-V3 — jugée sur le jeu 8",
        "",
        "V2 reste figée. V3 est un module séparé qui durcit trois règles :",
        "terme d'objet le plus **spécifique** exigé (pesé par sa rareté dans la",
        "source), objet concurrent valant désaveu, et noms composés comparés",
        "tête **et** qualificatif — « Villeneuve-sur-Loire » n'est pas",
        "« Villeneuve-les-Bains ».",
        "",
        "**Jeu 8**, indépendant, écrit et commité avant exécution. Univers neuf",
        "(clinique vétérinaire), 18 cas dont **huit corrects**, quatre d'entre",
        "eux conçus contre V3 elle-même : durcir des règles fait courir un",
        "risque de faux rejet, et c'est ce risque qu'il fallait mesurer.",
        "",
        "| Version | Bonnes conservées | Mauvaises rejetées | Faux rejets | Exactitude |",
        "|---|---|---|---|---|",
        "| sans contrôle | 8/8 | 0/10 | 0 | 44 % |",
        "| CONTEXT-V2 | 8/8 | 6/10 | 0 | 78 % |",
        "| **CONTEXT-V3** | 7/8 | **10/10** | **1** | **94 %** |",
        "",
        "V3 rejette **tous** les pièges, y compris l'homonymie de lieux que V2",
        "ne savait pas trancher. Elle introduit en revanche un défaut que V2",
        "n'avait pas.",
        "",
        "### Le faux rejet, et pourquoi il n'est pas corrigé",
        "",
        "`ok_nom_sans_qualificatif` : la source écrit « clinique de Villeneuve »",
        "là où la question dit « Villeneuve-sur-Loire ». Elle **abrège** ; V3 y",
        "lit une contradiction et rejette une information correcte.",
        "",
        "C'est le prix de la troisième règle, et le jeu 8 l'a attrapé parce",
        "qu'il avait été écrit pour ça. Le corriger maintenant reviendrait à",
        "s'entraîner sur l'examen qu'on vient de passer : ce sera CONTEXT-V4,",
        "sur un jeu 9 écrit avant son exécution.",
        "",
        "Un test fige ce faux rejet, et un autre fige une propriété assumée : la",
        "spécificité se mesure **dans la source**, donc une page d'une seule",
        "ligne relâche le contrôle d'objet. Une vraie pondération demanderait un",
        "corpus de fréquences, que ce système n'a pas.",
        "",
        "*(Sur le jeu 7 — devenu jeu de développement — V3 obtient 100 %. Ce",
        "chiffre n'est pas un résultat : on ne s'examine pas sur ses brouillons.)*",
        "",
        "## 6. La correction tentée, et rejetée",
        "",
        "Consignée ici parce qu'elle fait partie du résultat : ce qui a été",
        "essayé, ce que ça a amélioré, ce que ça a cassé, et pourquoi elle n'est",
        "pas dans le code.",
        "",
        "**Ce qui a été tenté.** Une fonction `_place_terms` propre à ce module,",
        "ne retenant que les **noms propres** comme termes de lieu, au lieu du",
        "repli sur les mots longs de `distinctive_terms` (côté RESEARCH-V2).",
        "",
        "**Le cas amélioré.** Pour une question sans nom propre — « combien",
        "coûte le tarif officiel du billet de guitare ? » — les termes d'objet",
        "passaient de l'ensemble vide à `{billet, guitare}`. Le contrôle d'objet,",
        "aujourd'hui désactivé sur ces questions, redevenait actif.",
        "",
        "**Le cas dégradé.** Sur la question « à quel prix le clou de girofle",
        "est-il acheté au planteur ? », le mot **planteur** devenait un terme",
        "d'objet. Une phrase parlant du prix de la **vanille** au planteur",
        "redevenait alors affirmable : un piège que la version mesurée bloque",
        "correctement se remettait à passer.",
        "",
        "**L'effet sur le jeu 7 : aucun.** Exactitude identique, 73 %, avant et",
        "après. Aucun gain mesurable, une régression avérée.",
        "",
        "**Pourquoi elle est rejetée.** Trois raisons, dans cet ordre :",
        "",
        "1. le résultat mesuré prime sur l'intuition — la correction ne gagnait",
        "   rien de mesurable et perdait quelque chose de vérifiable ;",
        "2. elle ne corrigeait pas le défaut, elle le déplaçait d'une catégorie",
        "   de questions à une autre ;",
        "3. l'ajuster après avoir vu le jeu 7 reviendrait à s'entraîner sur son",
        "   propre examen.",
        "",
        "## 7. Règle pour la suite",
        "",
        "Toute amélioration devient **CONTEXT-V4**, évaluée sur un **jeu 9**",
        "indépendant, écrit avant son exécution. V2 et V3 sont figées telles que",
        "mesurées ; les jeux 7 et 8 ne servent plus à juger, seulement à",
        "constater une régression.",
        "",
        "## 8. Limites restantes",
        "",
        "- Le mécanisme est **mesuré, pas adopté**. Il n'est branché sur aucune",
        "  version en production : cela demande une décision.",
        "- Le contrôle d'objet est trop permissif (voir ci-dessus).",
        "- Une question sans nom propre voit tous ses mots longs traités comme",
        "  des identifiants, ce qui **désactive** le contrôle d'objet. Aucun cas",
        "  du jeu 7 n'est concerné ; la faille est réelle et figée par un test.",
        "- Le seuil d'ancienneté est de deux ans, fixé a priori. Il conviendrait",
        "  mal à un domaine qui bouge chaque mois.",
        "- Le jeu 7 est écrit par l'auteur du système, comme les six autres.",
        "",
        f"*(États disponibles : {', '.join(STATES)}.)*",
    ])


__all__ = ["render"]
